/* Agent Station environment for static and mobile software agents
 * Copyright (C) 2022  Dr Christos Bohoris
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * connectina.co.uk/agent-station
 */
package uk.co.connectina.agentstation.exampleagents.linux;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 * A dialog used to report information on the apt update carried out.
 *
 * @author Dr Christos Bohoris
 */
public class AptUpdateReportDialog extends javax.swing.JDialog {

    /**
     * Creates new form AptUpdateReportDialog
     */
    public AptUpdateReportDialog(String report, String info, String error) {
        super((JFrame)null, true);
        initComponents();

        setTitle("Report");
        outcomeLabel.setText(report);
        infoTextArea.setText(info);
        infoTextArea.setCaretPosition(0);
        errorTextArea.setText(error);
        errorTextArea.setCaretPosition(0);
        closeButton.addActionListener(new CloseListener());
        getRootPane().setDefaultButton(closeButton);
        closeButton.revalidate();
        
        setSize(650, 450);
        setLocationRelativeTo(null);
    }

    public void display() {
        setVisible(true);
    }
    
    public class CloseListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent event) {
            setVisible(false);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.JPanel titlePanel = new javax.swing.JPanel();
        outcomeLabel = new javax.swing.JLabel();
        javax.swing.JTabbedPane reportTabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel infoPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        javax.swing.JPanel errorPanel = new javax.swing.JPanel();
        javax.swing.JScrollPane errorScrollPane = new javax.swing.JScrollPane();
        errorTextArea = new javax.swing.JTextArea();
        javax.swing.JPanel controlPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 6, 11));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        titlePanel.add(outcomeLabel);

        mainPanel.add(titlePanel, java.awt.BorderLayout.NORTH);

        infoPanel.setLayout(new java.awt.BorderLayout());

        infoTextArea.setEditable(false);
        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        infoScrollPane.setViewportView(infoTextArea);

        infoPanel.add(infoScrollPane, java.awt.BorderLayout.CENTER);

        reportTabbedPane.addTab("Information", infoPanel);

        errorPanel.setLayout(new java.awt.BorderLayout());

        errorTextArea.setEditable(false);
        errorTextArea.setColumns(20);
        errorTextArea.setRows(5);
        errorScrollPane.setViewportView(errorTextArea);

        errorPanel.add(errorScrollPane, java.awt.BorderLayout.CENTER);

        reportTabbedPane.addTab("Errors", errorPanel);

        mainPanel.add(reportTabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        controlPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 11, 11));
        controlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        controlPanel.add(closeButton);

        getContentPane().add(controlPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea errorTextArea;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel outcomeLabel;
    // End of variables declaration//GEN-END:variables
}
